language: node_js
node_js:
  - "node"
notifications:
  email: false
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
  - npm run build
script: 
  - npm run cypress:CI

  # //comment